### PR TITLE
[FEAT]: add pathfinder [async and not async] for entities IA

### PR DESCRIPTION
**Pull request by Refaltor77**

### CODE REVIEW

**Comment by AzaleeX** [comment]
Good evening @Refaltor77

First of all, thank you for contributing to the entities IA (#4)

**I'll look into it and give you a more detailed answer tomorrow** 

### Thanks again for your contribution 💖

**Comment by Virvolta** [comment]
The AsyncTask class is already used for compression by pocketmine. Ideally, we'd like to have another thread extension to lighten the one used by pocketmine. And we'd have to place it elsewhere than in src/poketmine/... rather in symply/... for better maintenance.

**Comment by Refaltor77** [comment]
The AI of the entities should be native to pocketmine, it should not be something to improve pocketmine precisely, the fact of using async task for its is totally justified and its fits within the framework of pocketmine, async task are reserved for pocketmine and its operations or for exceptionnally small operations in a plugin but its will not affect the understanding of the world because the path search is a quick, you didn’t read the outline of AsyncTask.php

**Comment by AzaleeX** [comment]
yes but this will lighten the thread

**Comment by Refaltor77** [comment]
open a thread for entities is very heavy, think of the fact that servers do not necessarily have much heart

**Comment by AzaleeX** [comment]
yes but often in the machine it does not only have 1 core after all I think that if you have a machine with 1 core it would be necessary to update or the 2nd solution would be to optimize in addition which already has the thread

**Comment by Refaltor77** [comment]
PocketMine offers to add basic workers in pocketmine.yml, so the async task concern is non-existent

**Pull request closed without merging**
