### PR TITLE
Tile/campfire

### LINKED ISSUE #4: Todo: List of missing blocks, items and Entity in Symply
> [!WARNING]
> This issue will be updated regularly to add blocks, items or entitys to the list.

# Block
   ### **Bamboo**
- [ ] Bamboo block - [Wiki](https://minecraft.fandom.com/wiki/Block_of_Bamboo)
- [ ] Stripped Bamboo - [Wiki](https://minecraft.fandom.com/wiki/Stripped_Bamboo)
- [ ] Bamboo Fence - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Fence)
- [ ] Bamboo Fence Gate - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Fence_Gate)
- [ ] Bamboo Wall Sign - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Wall_Sign)
- [ ] Bamboo Mosaic - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Mosaic)
    - [ ] Bamboo Mosaic Slab - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Mosaic)
    - [ ] Bamboo Mosaic Stairs - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Mosaic)
- [ ] Bamboo Slab - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Slab)
- [ ] Bamboo Stairs - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Stairs)
- [ ] Bamboo Planks - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Planks)
- [ ] Bamboo Pressure Plate - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Pressure_Plate)
- [ ] Bamboo Trapdoor - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Trapdoor)
- [ ] Bamboo Button - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Button)
- [ ] Bamboo Door - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Door)
- [ ] Bamboo Button - [Wiki](https://minecraft.fandom.com/wiki/Bamboo_Button)

# Natural
- [ ] Seagrass - [Wiki](https://minecraft.fandom.com/wiki/Seagrass)
- [ ] Pointed Dripstone - [Wiki](https://minecraft.fandom.com/wiki/Pointed_Dripstone)
- [ ] Dripstone Block - [Wiki](https://minecraft.fandom.com/wiki/Dripstone_Block)
- [ ] Azalea - [Wiki](https://minecraft.fandom.com/wiki/Azalea)
    - [ ] Flowering Azalea - [Wiki](https://minecraft.fandom.com/wiki/Flowering_Azalea)
- [ ] Infested Deepslate - [Wiki](https://minecraft.fandom.com/wiki/Infested_Deepslate)
- [ ] Sea Turtle Egg - [Wiki](https://minecraft.fandom.com/wiki/Sea_Turtle_Egg)
- [ ] Sniffer Egg - [Wiki](https://minecraft.fandom.com/wiki/Sniffer_Egg)
- [ ] Frogspawn - [Wiki](https://minecraft.fandom.com/wiki/Frogspawn)
- [ ] Bee Nest - [Wiki](https://minecraft.fandom.com/wiki/Bee_Nest)
- [ ] Beehive - [Wiki](https://minecraft.fandom.com/wiki/Beehive)
- [ ] Suspicious Sand - [Wiki](https://minecraft.fandom.com/wiki/Suspicious_Sand)
- [ ] Suspicious Gravel - [Wiki](https://minecraft.fandom.com/wiki/Suspicious_Gravel)

### **Moss**
- [ ] Moss Block - [Wiki](https://minecraft.fandom.com/wiki/Moss_Block)
- [ ] Moss Carpet - [Wiki](https://minecraft.fandom.com/wiki/Moss_Carpet)

# Biome
### **Sculk**
- [ ] Sculk Vein - [Wiki](https://minecraft.fandom.com/wiki/Sculk_Vein)
- [ ] Sculk Catalyst - [Wiki](https://minecraft.fandom.com/wiki/Sculk_Catalyst)
- [ ] Sculk Shrieker - [Wiki](https://minecraft.fandom.com/wiki/Sculk_Shrieker)
- [ ] Sculk Sensor - [Wiki](https://minecraft.fandom.com/wiki/Sculk_Sensor)
- [ ] Calibrated Sculk Sensor - [Wiki](https://minecraft.fandom.com/wiki/Calibrated_Sculk_Sensor)

### **Nether**
- [ ] Crimson Nylium - [Wiki](https://minecraft.fandom.com/wiki/Crimson_Nylium)
- [ ] Warped Nylium - [Wiki](https://minecraft.fandom.com/wiki/Warped_Nylium)
- [ ] Crimson Fungus - [Wiki](https://minecraft.fandom.com/wiki/Crimson_Fungus)
- [ ] Warped Fungus - [Wiki](https://minecraft.fandom.com/wiki/Warped_Fungus)

# Other
- [ ] Scaffolding - [Wiki](https://minecraft.fandom.com/wiki/Scaffolding)
- [ ] Honey Block - [Wiki](https://minecraft.fandom.com/wiki/Honey_Block)
- [ ] Lodestone - [Wiki](https://minecraft.fandom.com/wiki/Lodestone)
- [ ] Campfire - [Wiki](https://minecraft.fandom.com/wiki/Campfire)
    - [ ] Soul Campfire - [Wiki](https://minecraft.fandom.com/wiki/Campfire)
- [ ] Respawn Anchor - [Wiki](https://minecraft.fandom.com/wiki/Respawn_Anchor)
- [ ] Composter - [Wiki](https://minecraft.fandom.com/wiki/Composter)

### **Hanging Sign**
- [ ] Hanging Sign - [Wiki](https://minecraft.fandom.com/wiki/Hanging_Sign)
   - [ ] Oak
   - [ ] Spruce 
   - [ ] Birch 
   - [ ] Jungle 
   - [ ] Acacia 
   - [ ] Dark Oak
   - [ ] Mangrove 
   - [ ] Cherry 
   - [ ] Bamboo
   - [ ] Crimson 
   - [ ] Warped

# Items
- [ ] Brush - [Wiki](https://minecraft.fandom.com/wiki/Brush)
- [ ] Music Disc (Pigstep) - [Wiki](https://minecraft.fandom.com/wiki/Music_Disc_(Pigstep))
- [ ] Music Disc (Relic) - [Wiki](https://minecraft.fandom.com/wiki/Music_Disc_(Relic))

# Entity
- [ ] Armor Stand - [Wiki](https://minecraft.fandom.com/wiki/Armor_Stand)

### PR DESCRIPTION
**Pull request by nicholass003**
### Description

This is an update to implement Campfire and Campfire Souls, I have tested it and it works. However, there are still some drawbacks such as cooking over a campfire and not being detected in the creative inventory. Maybe there is some help to make it better, I think it is very helpful.

### Issue Resolved (if applicable)

Related to Campfire & Soul Campfire https://github.com/SymplyX/Symply/issues/4

### Proposed Changes

- Implement Campfire and Soul Campfire to complete https://github.com/SymplyX/Symply/issues/4

### Screenshots / Videos (if applicable, obligatory)

campfire-symply

### Verification

- [x] I have tested these changes locally
- [ ] Changes work as intended
- [ ] I have checked that these changes do not cause regression in other parts of the codebase

### Checklist

- [ ] I have added comments/documentation to explain the changes (if necessary)
- [ ] I have updated existing documentation if changes were required
- [x] I have ensured my code adheres to project style conventions and best practices

### CODE REVIEW

**Comment by AzaleeX** [comment]
Hi @nicholass003 ! 

### Thank you for your contribution 💖. 

I can't accept this pull request at the moment. It seems that it could create conflicts with **`Pocketmine-MP`** in the files, which is not our intention. However, **in the next three hours, a new pull request will be opened to implement our behaviour management system.**  `This PR will implement the creation of custom items/blocks in our API. `

- When the update is available, can you move your modifications to the `symply/blocks` folder?
   - That way I can pass your pull request to confirmed

**Comment by nicholass003** [comment]
> Hi @nicholass003 !
> 
> ### Thank you for your contribution 💖.
> I can't accept this pull request at the moment. It seems that it could create conflicts with **`Pocketmine-MP`** in the files, which is not our intention. However, **in the next three hours, a new pull request will be opened to implement our behaviour management system.** `This PR will implement the creation of custom items/blocks in our API. `
> 
> * When the update is available, can you move your modifications to the `symply/blocks` folder?
>   
>   * That way I can pass your pull request to confirmed

So for this implementation Symply has its own folder to add missing items and blocks?
And how about header comment and where should i store the block or item ids? Will it start from a certain number?

**Comment by AzaleeX** [comment]
hi @nicholass003 ,
I understand that you have this question but logical my colleague @SenseiTarzan must implement the system like that of pocketmine, in any case a kind 😉

**Comment by SenseiTarzan** [comment]
> > Hi @nicholass003 !
> > ### Thank you for your contribution 💖.
> > I can't accept this pull request at the moment. It seems that it could create conflicts with **`Pocketmine-MP`** in the files, which is not our intention. However, **in the next three hours, a new pull request will be opened to implement our behaviour management system.** `This PR will implement the creation of custom items/blocks in our API. `
> > 
> > * When the update is available, can you move your modifications to the `symply/blocks` folder?
> >   
> >   * That way I can pass your pull request to confirmed
> 
> So for this implementation Symply has its own folder to add missing items and blocks? And how about header comment and where should i store the block or item ids? Will it start from a certain number?

you can make your system in the next-dev all is available

**Comment by AzaleeX** [comment]
Hi @nicholass003,

Thank you very much for your contribution regarding the implementation of fire camps and the Nether in Symply for Minecraft Bedrock. ❤️

**You have up to a week to make these adjustments. If no response is received by then, I'll be forced to close the pull request.**

Your commitment and contributions are greatly appreciated. If you have any questions or concerns, don't hesitate to share them on our [discord](https://discord.gg/jA23KBqu3g).

**Pull request closed without merging**
